AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create KMS'
Parameters:
  
  Environment:
    Description: "The Environment Name that will be used to create the stack."
    Type: String

  Customer:
    Type: String

  Application:
    Description: Application Name. Intended for DB and other use
    Type: String

  Region:
    Description: Region Name. 
    Type: String
    
  KeyName:
    Description: KMS Name. 
    Type: String
    
  AliasName:
    Description: Alias Name. 
    Type: String

  PendingWindowInDays:
    Description: 'Specifies the number of days you want to retain the key.'
    Type: Number
    AllowedValues: [7, 14, 30]

Resources:

  Key:
    Type: AWS::KMS::Key
    Properties: 
      Description: 'Arina TST Key'
      Enabled: true
      PendingWindowInDays: !Ref PendingWindowInDays
      KeyPolicy: 
        Version: '2012-10-17'
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: 'kms:*'
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            Service: !Sub 'logs.${AWS::Region}.amazonaws.com'
          Action:
          - 'kms:Encrypt*'
          - 'kms:Decrypt*'
          - 'kms:ReEncrypt*'
          - 'kms:GenerateDataKey*'
          - 'kms:Describe*'
          Resource: '*'
          Condition:
            ArnEquals:
              kms:EncryptionContext:aws:logs:arn: 
                - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
                
                
        - Sid: Allow CloudTrail to encrypt logs
          Effect: Allow
          Principal:
            Service:
              - cloudtrail.amazonaws.com
          Action: 
          - 'kms:GenerateDataKey*'
          - 'kms:Describe*'
          - kms:Decrypt
          Resource: '*'
          Condition:
            StringLike:
              'kms:EncryptionContext:aws:cloudtrail:arn': !Sub 'arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*'

      Tags:
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Customer"
          Value: !Ref Customer
        -
          Key: "Application"
          Value: !Ref Application
        -
          Key: "Region"
          Value: !Ref Region
        -
          Key: "Name"
          Value: !Ref KeyName
        
  KeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Ref AliasName
      TargetKeyId: !Ref Key
            
Outputs:
  KeyAlias:
    Description: Key Alias
    Value: !Ref KeyAlias
    
  Key:
    Description: Key
    Value: !Ref Key            
    
  KeyArn:
    Description: Key
    Value: !GetAtt 
      - Key
      - Arn